name: Build and Publish

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.6.3
        with:
          branch: gh-pages
          folder: composeApp/build/dist/wasmJs/productionExecutable
          clean: true